### ISSUE TITLE
GQ Client/Server 0.10.0 Pre 4 - Stations disappear from display after a few minutes

### ISSUE THREAD

**Issue by andyaz** [xspanger3770/GlobalQuake#167]
GQ Client/Server 0.10.0 Pre 4 - Stations disappear from display after a few minutes. Console window shows "Station Index Has Changed!" when it happens. Restart the client and connect to server and stations return for a few minutes until it happens again.
![Stations Dissappearing 1](https://github.com/xspanger3770/GlobalQuake/assets/19541773/29a2ff4f-2074-4652-8e67-914514d22f1e)
![Stations Dissappearing 2](https://github.com/xspanger3770/GlobalQuake/assets/19541773/8b0e0b1d-3f40-4237-a73f-85810077b1da)

**Comment by andyaz** [comment]
Additional info. I have 5200 stations feeding, perhaps related to large number of stations?

**Comment by andyaz** [comment]
I am unsure if this is related but the console is full of these error messages

![Capture](https://github.com/xspanger3770/GlobalQuake/assets/19541773/35ddc95d-6e29-49bd-9d9e-55499fc4e09c)

**Comment by xspanger3770** [comment]
This really looks like a bug. I will try to investigate later today.

**Comment by xspanger3770** [comment]
Isn't there some error also in the server's console?

**Comment by andyaz** [comment]
Hi Jakub - There is no indication of issues in the server side console. Below is a capture from the console on the server. Here you see when I closed the client we got the expected socket error. Then you see the client reconnect as Client 8. About 2 minutes after the reconnect all the stations dissappeared from the client display but nothing was shown in the console window:

[10:59:28] ERROR: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:961)
        at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2886)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3213)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3223)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1695)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
        at gqserver.api.ServerClient.readPacket(ServerClient.java:53)
        at gqserver.server.ClientReader.run(ClientReader.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
[10:59:31] WARN: Not updating because: PREVIOUS_WAS_BETTER
[10:59:31] INFO: Hypocenter finding finished in: 56 ms
[10:59:31] INFO: Client #7 disconnected due to timeout
[10:59:37] INFO: A new client is joining...
[10:59:37] INFO: Performing handshake for client #8
[10:59:38] INFO: Client #8 handshake successfull
[10:59:40] INFO: Hypocenter finding finished in: 73 ms
[10:59:40] INFO: Hypocenter finding finished in: 71 ms
[10:59:44] INFO: Hypocenter finding finished in: 96 ms
[10:59:46] INFO: Hypocenter finding finished in: 93 ms
[10:59:53] WARN: Not updating because: PREVIOUS_WAS_BETTER
[10:59:53] INFO: Hypocenter finding finished in: 130 ms
[10:59:55] INFO: Hypocenter finding finished in: 89 ms
[10:59:56] WARN: Not updating because: PREVIOUS_WAS_BETTER
[10:59:56] INFO: Hypocenter finding finished in: 114 ms
[11:01:26] WARN: Not updating because: PREVIOUS_WAS_BETTER
[11:01:26] INFO: Hypocenter finding finished in: 96 ms
[11:01:54] WARN: Not updating because: PREVIOUS_WAS_BETTER
[11:01:54] INFO: Hypocenter finding finished in: 108 ms
[11:02:00] WARN: Not updating because: PREVIOUS_WAS_BETTER
[11:02:00] INFO: Hypocenter finding finished in: 138 ms
[11:02:44] INFO: Hypocenter finding finished in: 170 ms
[11:03:10] INFO: Hypocenter finding finished in: 34 ms
[11:04:00] INFO: Hypocenter finding finished in: 78 ms
[11:04:01] INFO: Hypocenter finding finished in: 114 ms
[11:04:01] WARN: Not updating because: PREVIOUS_WAS_BETTER
[11:04:01] INFO: Hypocenter finding finished in: 147 ms
[11:04:01] INFO: Hypocenter finding finished in: 119 ms

**Comment by andyaz** [comment]
Here are some screenshots of the server window to provide additional context for you.

![Capture](https://github.com/xspanger3770/GlobalQuake/assets/19541773/a74f95bd-6cd1-432c-a077-4d50b53efc87)
![Capture1](https://github.com/xspanger3770/GlobalQuake/assets/19541773/a0910db0-c690-49df-bd0e-6d490077fd2f)
![Capture2](https://github.com/xspanger3770/GlobalQuake/assets/19541773/55e3a078-504a-4335-957a-556e8027b939)

**Comment by xspanger3770** [comment]
Hmm that's really weird, I never had this issue happen to me and I'm running 3000 stations on my local server... There is really no error in the server console, but some errors might be hidden in the code by mistake..

**Comment by xspanger3770** [comment]
Also the "station indexing reset" message should only appear once in the client unless the server has been restarted, so if it appears more times there is definitely something wrong

**Comment by andyaz** [comment]
Also with that box unchecked I see flashing activity indications on the grayed out stations.
![Capture](https://github.com/xspanger3770/GlobalQuake/assets/19541773/87ed0d2a-3ef9-4d05-9d72-3cf5f9d18a4d)

**Comment by xspanger3770** [comment]
Oh I see.. maybe you have different timezone settings on client and server?

**Comment by xspanger3770** [comment]
or maybe the time itself got desynchronized either on the server or in client

**Comment by andyaz** [comment]
Both computers are in America Los Angeles tz and time is synchronized to my local stratum 1 GPS NTP so clocks should not be an issue. If the client server is reliant on time zones that would be bad for the scenario of server in one tz and clients in others. I would think you should have based all timestamps on UTC...

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xspanger3770** [comment]
Can you try hovering your mouse over a station and see the delay displayed below?

**Comment by andyaz** [comment]
I will try that when I get back from lunch.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andyaz** [comment]
Zoom and right click shows no data when all are grayed out.. When I restart the client and look while they are blue the delays are counting up until they go gray. Even my lowest delay stations on the AM network from my own seedlink in local mode only show about 1 to 4 seconds delay, the delay just ticks up. It looks like it gets the initial data indexed and then times out like it never sees any station data again. 
Every other part of the client display appears to function properly including the green flashing boxes for triggered stations come and go. If I enable "Last Data Time" on the client it is visibly in sync with the system clock to the second by eye.

FYI - I did verify that both server and client are in sync with the Stratum 1 GPS clock so if there is a clock difference it is in milliseconds...

**Comment by andyaz** [comment]
II take back the statement about the station trigger flashing squares. They are stuck in the state last seen and are not changing over time. If they were flashing trigger at the time of the data timeout they are remaining in that state.

**Comment by YacineBoussoufa** [comment]
Have you tried seeing if the Firewall is blocking GlobalQuake? 
The flashing beein stuck in the last data recorded, happens to me when my internet crashes. 
So probably something either blocking the connection (like the firewall), or another service using the same port of GlobalQuake, and creating a conflict.

**Comment by andyaz** [comment]
> Have you tried seeing if the Firewall is blocking GlobalQuake? The flashing beein stuck in the last data recorded, happens to me when my internet crashes. So probably something either blocking the connection (like the firewall), or another service using the same port of GlobalQuake, and creating a conflict.

Arrrgggghhh!!!!  You are a genius Yacine... When the port changed to 38000 something in one of the boxes windows firewalls must have been partially blocking things. I set it back to 12345 on both ends and now it works. I will investigate further to get it on the new recommended port. Great catch I had not thought about since both boxes are on the same subnet with no firewalls between them. I did not think to look at the Win Firewalls. DOH!

**Comment by andyaz** [comment]
I will close this...
