### ISSUE TITLE
Settings & Calibration Suddenly Broken

### ISSUE THREAD

**Issue by kimuyukix** [xspanger3770/GlobalQuake#290]
java.lang.ExceptionInInitializerError
	at globalquake.core.Settings.save(Settings.java:502)
	at globalquake.core.Settings.<clinit>(Settings.java:183)
	at globalquake.ui.settings.GeneralSettingsPanel.createHomeLocationSettings(GeneralSettingsPanel.java:127)
	at globalquake.ui.settings.GeneralSettingsPanel.<init>(GeneralSettingsPanel.java:33)
	at globalquake.ui.settings.SettingsFrame.addPanels(SettingsFrame.java:118)
	at globalquake.ui.settings.SettingsFrame.initialize(SettingsFrame.java:109)
	at globalquake.ui.settings.SettingsFrame.<init>(SettingsFrame.java:50)
	at globalquake.ui.client.MainFrame.lambda$createButtons$4(MainFrame.java:168)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NumberFormatException: empty String
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:476)
	at java.base/java.lang.Float.valueOf(Float.java:440)
	at globalquake.core.HypocsSettings.load(HypocsSettings.java:31)
	at globalquake.core.HypocsSettings.<clinit>(HypocsSettings.java:18)
	... 43 more

I have ... no idea what I'm looking at. All I know is, settings and calibration are broken. Therefore I can't open GlobalQuake either by .exe or .jar. I've restarted and updated and restarted my computer; I've cleaned the RAM; I've performed malware and virus scans; and I've reinstalled GlobalQuake twice, all to no avail. "43 more" errors...m'kay, great, where do I find the log? Also, how do I fix this? And how did it get broken in the first place?

**Comment by kimuyukix** [comment]
Playground Mode also compromised.

**Comment by ekomrak** [comment]
Based on the stack trace you provided I see that "Home Latitude" parameter (Options-> Settings -> General) is empty. Please fill it with any numeric value.

**Comment by kimuyukix** [comment]
It appears that wasn't my only problem. Your suggestion and deleting the
content of the other .properties file in the main data folder
(hypocs.properties) resolved my issue. Thanks for your help!
