### ISSUE TITLE
Error at start, cannot load sounds

### ISSUE THREAD

**Issue by lucaquakes** [xspanger3770/GlobalQuake#306]
globalquake.core.exception.FatalIOException: Unable to create main directory!
	at globalquake.main.Main.initMainDirectory(Main.java:69)
	at globalquake.main.Main.main(Main.java:26)

**Comment by WalkTheEarth** [comment]
where do you have gq saved?

**Comment by xspanger3770** [comment]
It is a part of windows file permissions issue that was fixed in 1.0.0
https://globalquake.net/download
