### ISSUE TITLE
Error when dragging Station Monitor window to minimum height

### ISSUE THREAD

**Issue by DopplerWx** [xspanger3770/GlobalQuake#314]
java.lang.IllegalArgumentException: w and h must be > 0
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:281)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:376)
	at globalquake.ui.StationMonitorPanel.updateImage(StationMonitorPanel.java:43)
	at globalquake.ui.StationMonitor$4.componentResized(StationMonitor.java:74)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6452)
	at java.desktop/java.awt.Component.processEvent(Component.java:6406)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Windows 10 running v0.11.0_pre-1

**Comment by xspanger3770** [comment]
Station monitor got a major redesign in 1.0.0. check it out at
https://globalquake.net/download
