### ISSUE TITLE
Unable to select stations and launch app if sounds haven't loaded

### ISSUE THREAD

**Issue by YacineBoussoufa** [xspanger3770/GlobalQuake#57]
I was trying to replicate the issue #56 on my Ubuntu in WSL, the version is not equipped with an Audio tunnel, therefore the sounds weren't able to load. This causes the app to "freeze" without the ability to select or launch the app itself. The messagge "Loading sounds..." stays forever
![image](https://github.com/xspanger3770/GlobalQuake/assets/46266665/0831f34b-99fb-4905-8089-6640f00cd983)

Error pane:
`globalquake.exception.FatalIOException: Cannot load sound: sounds/countdown/countdown_04.wav
	at globalquake.sounds.Sounds.loadSound(Sounds.java:40)
	at globalquake.sounds.Sounds.load(Sounds.java:68)
	at globalquake.main.Main.initAll(Main.java:71)
	at globalquake.main.Main$1.run(Main.java:51)
Caused by: javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 48000.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:484)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1241)
	at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:115)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1038)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1134)
	at globalquake.sounds.Sounds.loadSound(Sounds.java:37)
	... 3 more
`

cmd log:
`Load successfull
false, javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 48000.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.`

It would be nice to allow the launch of the app without sounds and print "Sounds not avaiable" at the bottom left near "Sound Alarms: Enabled (S)"

**Comment by xspanger3770** [comment]
Oh god... so many downloads today and the bugs are starting to pop up :D

**Comment by DecryptingElectrons** [comment]
This is something i would like to work on!
